server:
  port: 9009

spring:
  application:
    name: GitHub-Wrapped
  data:
    mongodb:
      uri: ${MONGODB_URI}
auth:
  token: ${GH_TOKEN}

github:
  graphql:
    url: https://api.github.com/graphql
  username: GITHUB_USERNAME
  token: ${GH_TOKEN}